### ISSUE TITLE
1.4.1 Lua Issue on launch

### ISSUE THREAD

**Issue by sbdragon89** [ExoticComet/Robot-World#5]
![image](https://user-images.githubusercontent.com/30519149/54787338-1e304100-4c34-11e9-964e-94310d23dd61.png)
get this pop up ever since 1.4.1, 1.4.0 worked fine until i updated. Tested with all mods disabled and just this one running.

**Comment by sbdragon89** [comment]
After downloading a 1.3 version and updating to the latest i was able to troubleshoot it further looks like it incompatibility with "Bob's Electronics"

**Comment by ExoticComet** [comment]
Resolved. Robot World wasn't able to find certain recipe entries in bobelectronics. Now using pre-defined prototypes with compatible recipes.
